spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sanwo_db
    password:
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect